export enum JdAutoCompleteType {
    tel = 'tel',
    email = 'email',
    address = 'address',
    off = 'password',
    firstName = 'given-name',
    lastName = 'family-name',
    newPassword = 'new-password',
    currentPassword = 'current-password',
    oneTimeCode = 'one-time-code',
    organization = 'organization',
    streetAddress = 'street-address',
    url = 'url',
    addressLine1 = 'address-line1',
    addressLine2 = 'address-line2',
    addressLine3 = 'address-line3',
}